# Configuração do Google App Engine
runtime: python310

# Configuração de escalonamento automático otimizada
automatic_scaling:
  min_instances: 0
  max_instances: 5
  min_idle_instances: 0
  max_idle_instances: 2
  min_pending_latency: 100ms
  max_pending_latency: 500ms
  max_concurrent_requests: 20

# Configuração de recursos (F1 para economizar custos)
instance_class: F1

# Variáveis de ambiente
env_variables:
  FLASK_ENV: "production"
  USE_GCS: "true"
  PYTHONPATH: "/opt/python/lib/python3.10/site-packages"

# Handlers para arquivos estáticos
handlers:
- url: /static
  static_dir: static
  secure: always
  expiration: "7d"
  http_headers:
    X-Content-Type-Options: "nosniff"
    X-Frame-Options: "DENY"
    X-XSS-Protection: "1; mode=block"
    Cache-Control: "public, max-age=604800"

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  secure: always
  expiration: "30d"

- url: /.*
  script: auto
  secure: always

# Health checks otimizados
readiness_check:
  path: "/health"
  check_interval_sec: 10
  timeout_sec: 4
  failure_threshold: 3
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Configurações de rede (opcional - remover se não usar VPC)
# vpc_access_connector:
#   name: projects/PROJECT_ID/locations/REGION/connectors/CONNECTOR_NAME
